export type Phase = 1 | 2 | 3
export type Category =
  | 'income-tax' | 'gst' | 'identity' | 'govt'
  | 'business' | 'accounting' | 'legal' | 'loans' | 'insurance'

export interface ServiceItem {
  slug:         string
  name:         string
  nameHindi:    string
  category:     Category
  emoji:        string
  desc:         string
  price:        number
  priceLabel:   string           // e.g. "₹99" or "₹999/mo"
  agentPrice:   string
  sla:          string
  caRequired:   boolean
  phase:        Phase
  popular?:     boolean
  recurring?:   boolean
  tags:         string[]
}

export const CATEGORY_META: Record<Category, { label: string; labelHindi: string; emoji: string; desc: string; color: string; bg: string }> = {
  'income-tax': { label: 'Income Tax',        labelHindi: 'आयकर',           emoji: '📄', desc: 'ITR filing, notices, audits, TDS',              color: 'text-blue-700',   bg: 'bg-blue-50 border-blue-200'   },
  'gst':        { label: 'GST',               labelHindi: 'GST',            emoji: '🏢', desc: 'Registration, returns, notices, refunds',       color: 'text-indigo-700', bg: 'bg-indigo-50 border-indigo-200'},
  'identity':   { label: 'PAN & Aadhaar',     labelHindi: 'PAN और आधार',    emoji: '🪪', desc: 'Applications, corrections, linking',            color: 'text-purple-700', bg: 'bg-purple-50 border-purple-200'},
  'govt':       { label: 'Govt Certificates', labelHindi: 'सरकारी प्रमाण', emoji: '🏛️', desc: 'Certificates, schemes, EPF, passport',          color: 'text-teal-700',   bg: 'bg-teal-50 border-teal-200'   },
  'business':   { label: 'Business Setup',    labelHindi: 'व्यवसाय',        emoji: '🏭', desc: 'Registration, licences, trademarks',            color: 'text-orange-700', bg: 'bg-orange-50 border-orange-200'},
  'accounting': { label: 'Accounting',        labelHindi: 'लेखांकन',        emoji: '📊', desc: 'Bookkeeping, payroll, P&L, CFO services',       color: 'text-green-700',  bg: 'bg-green-50 border-green-200' },
  'legal':      { label: 'Legal Documents',   labelHindi: 'कानूनी दस्तावेज़', emoji: '⚖️', desc: 'Agreements, notices, affidavits, RTI',        color: 'text-red-700',    bg: 'bg-red-50 border-red-200'     },
  'loans':      { label: 'Loans & Credit',    labelHindi: 'लोन',             emoji: '💰', desc: 'CIBIL, Mudra, bank loan docs, subsidies',      color: 'text-amber-700',  bg: 'bg-amber-50 border-amber-200' },
  'insurance':  { label: 'Insurance',         labelHindi: 'बीमा',            emoji: '🛡️', desc: 'Life, health, motor, claims assistance',       color: 'text-cyan-700',   bg: 'bg-cyan-50 border-cyan-200'   },
}

export const ALL_SERVICES: ServiceItem[] = [
  // ── INCOME TAX ────────────────────────────────────────────────
  { slug:'itr-1',        name:'ITR-1 Filing',              nameHindi:'ITR-1 दाखिल',      category:'income-tax', emoji:'📄', desc:'Salaried employees with single Form-16, no capital gains',              price:99,    priceLabel:'₹99',      agentPrice:'₹500–₹1,500',  sla:'24 hrs',  caRequired:false, phase:1, popular:true,  tags:['salaried','form16','refund'] },
  { slug:'itr-2',        name:'ITR-2 Filing',              nameHindi:'ITR-2 दाखिल',      category:'income-tax', emoji:'📄', desc:'Capital gains, multiple properties, FD income, foreign income',          price:299,   priceLabel:'₹299',     agentPrice:'₹999–₹2,000',  sla:'48 hrs',  caRequired:true,  phase:1, popular:true,  tags:['capital gains','shares','property'] },
  { slug:'itr-3',        name:'ITR-3 Filing',              nameHindi:'ITR-3 दाखिल',      category:'income-tax', emoji:'📄', desc:'Business or profession income, non-presumptive basis',                  price:599,   priceLabel:'₹599',     agentPrice:'₹1,500–₹3,000',sla:'48 hrs',  caRequired:true,  phase:2,               tags:['business income','professional'] },
  { slug:'itr-4',        name:'ITR-4 / Sugam',             nameHindi:'ITR-4 Sugam',       category:'income-tax', emoji:'📄', desc:'Presumptive income for traders, freelancers, contractors 44AD/44ADA',   price:399,   priceLabel:'₹399',     agentPrice:'₹800–₹2,000',  sla:'48 hrs',  caRequired:true,  phase:2,               tags:['presumptive','trader','freelancer'] },
  { slug:'revised-itr',  name:'Revised ITR Filing',        nameHindi:'संशोधित ITR',       category:'income-tax', emoji:'🔄', desc:'Correct mistakes in an already-filed return before the deadline',       price:199,   priceLabel:'₹199',     agentPrice:'₹500–₹1,200',  sla:'24 hrs',  caRequired:false, phase:2, popular:true,  tags:['correction','mistake','refile'] },
  { slug:'belated-itr',  name:'Belated ITR Filing',        nameHindi:'विलंबित ITR',       category:'income-tax', emoji:'⏰', desc:'File after 31 July deadline — penalty calculated and minimised',        price:249,   priceLabel:'₹249',     agentPrice:'₹600–₹1,500',  sla:'24 hrs',  caRequired:false, phase:2,               tags:['late filing','penalty','deadline'] },
  { slug:'notice-reply', name:'Tax Notice Reply',          nameHindi:'नोटिस का जवाब',    category:'income-tax', emoji:'⚠️', desc:'143(1), 148, 139(9) defective return — expert response drafted',        price:599,   priceLabel:'₹599',     agentPrice:'₹2,000–₹5,000',sla:'5 days',  caRequired:true,  phase:2, popular:true,  tags:['notice','143','defective'] },
  { slug:'it-appeal',    name:'IT Appeal (CIT-A)',         nameHindi:'आयकर अपील',         category:'income-tax', emoji:'⚖️', desc:'Filing appeal against Income Tax Department orders at CIT(A)',          price:2499,  priceLabel:'₹2,499',   agentPrice:'₹8,000–₹20,000',sla:'7 days', caRequired:true,  phase:3,               tags:['appeal','tribunal','dispute'] },
  { slug:'advance-tax',  name:'Advance Tax Calculation',   nameHindi:'अग्रिम कर',         category:'income-tax', emoji:'🧮', desc:'Quarterly advance tax estimate and challan generation',                price:199,   priceLabel:'₹199',     agentPrice:'₹300–₹800',    sla:'Same day',caRequired:false, phase:1,               tags:['advance tax','challan','quarterly'] },
  { slug:'form26as',     name:'Form 26AS / AIS Review',    nameHindi:'26AS जांच',         category:'income-tax', emoji:'🔍', desc:'Check and reconcile TDS credits, AIS discrepancies',                   price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'Same day',caRequired:false, phase:1,               tags:['TDS','credit','26AS','AIS'] },
  { slug:'refund-track', name:'Refund Status & Follow-up', nameHindi:'रिफंड ट्रैकिंग',   category:'income-tax', emoji:'💸', desc:'Track stuck refunds and escalate with the Income Tax Department',      price:149,   priceLabel:'₹149',     agentPrice:'₹300–₹700',    sla:'Same day',caRequired:false, phase:1, popular:true,  tags:['refund','status','tracking'] },
  { slug:'tds-return',   name:'TDS Return Filing',         nameHindi:'TDS रिटर्न',        category:'income-tax', emoji:'📋', desc:'Quarterly TDS returns for employers — 24Q, 26Q, 27Q',                  price:799,   priceLabel:'₹799',     agentPrice:'₹1,500–₹3,000',sla:'48 hrs',  caRequired:true,  phase:2, recurring:true, tags:['TDS','employer','quarterly'] },
  { slug:'tan-reg',      name:'TAN Registration',          nameHindi:'TAN रजिस्ट्रेशन',  category:'income-tax', emoji:'🔢', desc:'Tax Deduction Account Number for businesses and employers',            price:299,   priceLabel:'₹299',     agentPrice:'₹500–₹1,000',  sla:'Same day',caRequired:false, phase:2,               tags:['TAN','employer','TDS'] },
  { slug:'form-15ca',    name:'Form 15CA/CB',              nameHindi:'विदेश भेजना',       category:'income-tax', emoji:'🌐', desc:'Foreign remittance certificates — CA certification included',          price:999,   priceLabel:'₹999',     agentPrice:'₹2,000–₹5,000',sla:'3 days',  caRequired:true,  phase:3,               tags:['foreign','NRI','remittance'] },
  { slug:'tax-audit',    name:'Tax Audit (44AB)',          nameHindi:'टैक्स ऑडिट',       category:'income-tax', emoji:'🔎', desc:'Mandatory audit for turnover above ₹1Cr — Form 3CB/3CD',               price:2999,  priceLabel:'₹2,999',   agentPrice:'₹8,000–₹25,000',sla:'7 days', caRequired:true,  phase:3,               tags:['audit','turnover','44AB'] },
  { slug:'audit-44ad',   name:'Audit u/s 44AD/44ADA',     nameHindi:'अनुमानित ऑडिट',    category:'income-tax', emoji:'🔎', desc:'Presumptive basis audit for small businesses opting out',              price:1999,  priceLabel:'₹1,999',   agentPrice:'₹5,000–₹15,000',sla:'7 days', caRequired:true,  phase:3,               tags:['audit','presumptive','44ADA'] },

  // ── GST ──────────────────────────────────────────────────────
  { slug:'gst-registration',name:'GST Registration',      nameHindi:'GST पंजीकरण',      category:'gst', emoji:'🏢', desc:'New GSTIN application — ARN tracking included',                        price:499,   priceLabel:'₹499',     agentPrice:'₹1,500–₹3,000',sla:'6 hrs',   caRequired:false, phase:1, popular:true,  tags:['GSTIN','business','new'] },
  { slug:'gst-cancel',   name:'GST Cancellation',         nameHindi:'GST रद्द',          category:'gst', emoji:'❌', desc:'Cancel GSTIN for businesses closing or below threshold',               price:399,   priceLabel:'₹399',     agentPrice:'₹800–₹1,500',  sla:'Same day',caRequired:false, phase:1,               tags:['cancel','close','GSTIN'] },
  { slug:'gstr-1',       name:'GSTR-1 Filing',            nameHindi:'GSTR-1 दाखिल',     category:'gst', emoji:'📋', desc:'Monthly/quarterly outward supply return',                              price:299,   priceLabel:'₹299',     agentPrice:'₹500–₹1,000',  sla:'Same day',caRequired:false, phase:2, recurring:true, tags:['outward','sales','monthly'] },
  { slug:'gstr-3b',      name:'GSTR-3B Filing',           nameHindi:'GSTR-3B दाखिल',    category:'gst', emoji:'📋', desc:'Monthly GST payment summary return',                                   price:299,   priceLabel:'₹299',     agentPrice:'₹500–₹1,000',  sla:'Same day',caRequired:false, phase:2, recurring:true, tags:['payment','monthly','ITC'] },
  { slug:'gstr-9',       name:'GSTR-9 Annual Return',     nameHindi:'GSTR-9 वार्षिक',   category:'gst', emoji:'📊', desc:'Annual GST reconciliation — GSTR-9 and 9C',                            price:999,   priceLabel:'₹999',     agentPrice:'₹3,000–₹8,000',sla:'5 days',  caRequired:true,  phase:3,               tags:['annual','reconciliation','9C'] },
  { slug:'gst-lut',      name:'GST LUT Filing',           nameHindi:'LUT',               category:'gst', emoji:'📤', desc:'Letter of Undertaking for exports without paying IGST',               price:499,   priceLabel:'₹499',     agentPrice:'₹800–₹2,000',  sla:'Same day',caRequired:false, phase:2,               tags:['export','LUT','IGST'] },
  { slug:'gst-notice',   name:'GST Notice Reply',         nameHindi:'GST नोटिस',         category:'gst', emoji:'⚠️', desc:'Show-cause notice, scrutiny, and demand reply',                        price:799,   priceLabel:'₹799',     agentPrice:'₹2,000–₹5,000',sla:'5 days',  caRequired:true,  phase:3,               tags:['notice','demand','SCN'] },
  { slug:'gst-refund',   name:'GST Refund Application',   nameHindi:'GST रिफंड',         category:'gst', emoji:'💰', desc:'Claim refund for exports, inverted duty, or excess payment',          price:699,   priceLabel:'₹699',     agentPrice:'₹2,000–₹5,000',sla:'5 days',  caRequired:true,  phase:3,               tags:['refund','export','ITC'] },
  { slug:'einvoice',     name:'E-Invoice Setup',          nameHindi:'E-Invoice',         category:'gst', emoji:'🔌', desc:'Configure e-invoicing compliance — required above ₹5Cr turnover',     price:399,   priceLabel:'₹399',     agentPrice:'₹800–₹2,000',  sla:'Same day',caRequired:false, phase:2,               tags:['e-invoice','B2B','IRP'] },
  { slug:'eway-bill',    name:'E-Way Bill Assistance',    nameHindi:'E-Way Bill',        category:'gst', emoji:'🚚', desc:'Generate and troubleshoot e-way bills for goods transport',            price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'Same day',caRequired:false, phase:1,               tags:['transport','goods','eway'] },
  { slug:'gst-recon',    name:'GST Reconciliation',       nameHindi:'GST मिलान',         category:'gst', emoji:'🔄', desc:'GSTR-2A vs books, ITC mismatch identification and resolution',        price:599,   priceLabel:'₹599',     agentPrice:'₹1,500–₹3,000',sla:'3 days',  caRequired:true,  phase:2,               tags:['ITC','mismatch','2A','reconciliation'] },

  // ── IDENTITY ─────────────────────────────────────────────────
  { slug:'pan-new',      name:'New PAN Application',      nameHindi:'नया PAN',            category:'identity', emoji:'🪪', desc:'Apply for a fresh PAN card — Form 49A',                           price:149,   priceLabel:'₹149',     agentPrice:'₹300–₹800',    sla:'Same day',caRequired:false, phase:1, popular:true,  tags:['PAN','new','Form49A'] },
  { slug:'pan-correct',  name:'PAN Correction / Update',  nameHindi:'PAN सुधार',          category:'identity', emoji:'✏️', desc:'Name, date of birth, or address corrections in PAN',              price:149,   priceLabel:'₹149',     agentPrice:'₹300–₹800',    sla:'Same day',caRequired:false, phase:1, popular:true,  tags:['PAN','correction','name','DOB'] },
  { slug:'pan-reprint',  name:'PAN Reprint / ePAN',       nameHindi:'PAN दोबारा',         category:'identity', emoji:'🖨️', desc:'Lost PAN reprint or instant ePAN download',                       price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'Same day',caRequired:false, phase:1,               tags:['lost','reprint','ePAN'] },
  { slug:'pan-aadhaar-link',name:'PAN–Aadhaar Linking',   nameHindi:'PAN-Aadhaar लिंक',  category:'identity', emoji:'🔗', desc:'Link PAN with Aadhaar, resolve name/DOB mismatches',              price:49,    priceLabel:'₹49',      agentPrice:'₹150–₹400',    sla:'1 hr',    caRequired:false, phase:1, popular:true,  tags:['linking','mismatch','deadline'] },
  { slug:'pan-nri',      name:'PAN for NRI / Foreign',    nameHindi:'NRI PAN',            category:'identity', emoji:'🌐', desc:'PAN card application for NRIs and foreign nationals — Form 49AA', price:299,   priceLabel:'₹299',     agentPrice:'₹500–₹1,500',  sla:'Same day',caRequired:false, phase:2,               tags:['NRI','foreign','49AA'] },
  { slug:'aadhaar-address',name:'Aadhaar Address Update', nameHindi:'आधार पता',          category:'identity', emoji:'🏠', desc:'Update address using electricity bill, rent agreement, or passbook',price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'2 hrs',   caRequired:false, phase:1, popular:true,  tags:['address','update','UIDAI'] },
  { slug:'aadhaar-name', name:'Aadhaar Name / DOB Update',nameHindi:'आधार नाम सुधार',    category:'identity', emoji:'✏️', desc:'Correct name or date of birth — centre booking guidance included',  price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'2 hrs',   caRequired:false, phase:1,               tags:['name','DOB','correction'] },
  { slug:'aadhaar-mobile',name:'Aadhaar Mobile Update',   nameHindi:'आधार मोबाइल',       category:'identity', emoji:'📱', desc:'Update or register mobile number — centre visit coordination',      price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'2 hrs',   caRequired:false, phase:2,               tags:['mobile','OTP','UIDAI'] },
  { slug:'aadhaar-centre',name:'Aadhaar Centre Booking',  nameHindi:'आधार केंद्र',       category:'identity', emoji:'📍', desc:'Book nearest Aadhaar enrolment or update centre appointment',       price:49,    priceLabel:'₹49',      agentPrice:'₹100–₹300',    sla:'Same day',caRequired:false, phase:1,               tags:['booking','centre','appointment'] },
  { slug:'epan-download',name:'ePAN Download',            nameHindi:'ePAN डाउनलोड',       category:'identity', emoji:'📥', desc:'Download ePAN from NSDL or UTIITSL portal instantly',              price:49,    priceLabel:'₹49',      agentPrice:'₹100–₹300',    sla:'Same day',caRequired:false, phase:1,               tags:['download','NSDL','UTIITSL'] },
  { slug:'digilocker',   name:'DigiLocker Setup',         nameHindi:'DigiLocker',         category:'identity', emoji:'☁️', desc:'Create account, link documents, fetch govt certificates',          price:79,    priceLabel:'₹79',      agentPrice:'₹150–₹400',    sla:'Same day',caRequired:false, phase:1,               tags:['digital','documents','govt'] },

  // ── GOVT CERTIFICATES ────────────────────────────────────────
  { slug:'income-cert',  name:'Income Certificate',       nameHindi:'आय प्रमाण पत्र',    category:'govt', emoji:'📜', desc:'State govt income certificate via e-district portal',              price:149,   priceLabel:'₹149',     agentPrice:'₹400–₹800',    sla:'2 days',  caRequired:false, phase:2,               tags:['certificate','income','state'] },
  { slug:'domicile',     name:'Domicile Certificate',     nameHindi:'निवास प्रमाण',       category:'govt', emoji:'🏡', desc:'Proof of permanent residence from tehsildar',                      price:149,   priceLabel:'₹149',     agentPrice:'₹400–₹700',    sla:'2 days',  caRequired:false, phase:2,               tags:['domicile','residence','tehsil'] },
  { slug:'caste-cert',   name:'Caste Certificate',        nameHindi:'जाति प्रमाण पत्र',   category:'govt', emoji:'📜', desc:'SC/ST/OBC certificate for government benefits and reservations',   price:199,   priceLabel:'₹199',     agentPrice:'₹500–₹1,000',  sla:'3 days',  caRequired:false, phase:2,               tags:['SC','ST','OBC','reservation'] },
  { slug:'police-noc',   name:'Police Verification / NOC',nameHindi:'पुलिस सत्यापन',     category:'govt', emoji:'👮', desc:'Character certificate or tenant verification NOC',                 price:149,   priceLabel:'₹149',     agentPrice:'₹400–₹800',    sla:'2 days',  caRequired:false, phase:2,               tags:['police','character','NOC','tenant'] },
  { slug:'birth-cert',   name:'Birth Certificate',        nameHindi:'जन्म प्रमाण पत्र',   category:'govt', emoji:'👶', desc:'Apply or correct birth certificate via municipality',              price:149,   priceLabel:'₹149',     agentPrice:'₹400–₹700',    sla:'2 days',  caRequired:false, phase:2,               tags:['birth','municipality','correction'] },
  { slug:'death-cert',   name:'Death Certificate',        nameHindi:'मृत्यु प्रमाण पत्र', category:'govt', emoji:'📜', desc:'Apply for death certificate or corrections',                       price:149,   priceLabel:'₹149',     agentPrice:'₹400–₹700',    sla:'2 days',  caRequired:false, phase:2,               tags:['death','certificate','family'] },
  { slug:'marriage-cert',name:'Marriage Certificate',     nameHindi:'विवाह प्रमाण पत्र',  category:'govt', emoji:'💍', desc:'Register and obtain official marriage certificate',                price:249,   priceLabel:'₹249',     agentPrice:'₹500–₹1,000',  sla:'3 days',  caRequired:false, phase:2,               tags:['marriage','registration','certificate'] },
  { slug:'ration-card',  name:'Ration Card Services',     nameHindi:'राशन कार्ड',          category:'govt', emoji:'🏪', desc:'New ration card, member addition/removal, corrections',            price:149,   priceLabel:'₹149',     agentPrice:'₹300–₹700',    sla:'2 days',  caRequired:false, phase:2,               tags:['ration','BPL','APL','card'] },
  { slug:'driving-lic',  name:'Driving Licence Services', nameHindi:'ड्राइविंग लाइसेंस', category:'govt', emoji:'🚗', desc:'LL, DL apply, renewal, address change, RC copy',                   price:199,   priceLabel:'₹199',     agentPrice:'₹400–₹1,000',  sla:'Same day',caRequired:false, phase:1, popular:true,  tags:['driving','DL','LL','renewal','RC'] },
  { slug:'voter-id',     name:'Voter ID Services',        nameHindi:'वोटर ID',             category:'govt', emoji:'🗳️', desc:'New enrolment, correction, deletion, online card',                 price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'Same day',caRequired:false, phase:1,               tags:['voter','EPIC','election'] },
  { slug:'passport',     name:'Passport Assistance',      nameHindi:'पासपोर्ट',            category:'govt', emoji:'🛂', desc:'Apply, renew, Tatkal — document guidance and slot booking',        price:349,   priceLabel:'₹349',     agentPrice:'₹700–₹2,000',  sla:'24 hrs',  caRequired:false, phase:1, popular:true,  tags:['passport','Tatkal','renewal','travel'] },
  { slug:'pmay',         name:'PMAY Application',         nameHindi:'PMAY आवास',           category:'govt', emoji:'🏠', desc:'Pradhan Mantri Awas Yojana — housing scheme application',          price:249,   priceLabel:'₹249',     agentPrice:'₹500–₹1,500',  sla:'2 days',  caRequired:false, phase:2,               tags:['housing','scheme','PMAY','subsidy'] },
  { slug:'ayushman',     name:'Ayushman Bharat Card',     nameHindi:'आयुष्मान भारत',       category:'govt', emoji:'🏥', desc:'PM-JAY health card apply, correct, or activate',                   price:99,    priceLabel:'₹99',      agentPrice:'₹200–₹500',    sla:'Same day',caRequired:false, phase:1,               tags:['health','insurance','PMJAY'] },
  { slug:'epf',          name:'EPF / PF Services',        nameHindi:'PF सेवाएं',           category:'govt', emoji:'💼', desc:'Withdrawal, transfer, UAN activation, passbook',                   price:199,   priceLabel:'₹199',     agentPrice:'₹400–₹1,000',  sla:'48 hrs',  caRequired:false, phase:1, popular:true,  tags:['PF','EPF','UAN','withdrawal','transfer'] },
  { slug:'esic',         name:'ESIC / ESI Services',      nameHindi:'ESIC सेवाएं',         category:'govt', emoji:'🏥', desc:'ESIC registration, dispensary mapping, claims',                    price:199,   priceLabel:'₹199',     agentPrice:'₹400–₹800',    sla:'2 days',  caRequired:false, phase:2,               tags:['ESIC','health','employer','claims'] },
  { slug:'scholarship',  name:'Scholarship Applications', nameHindi:'छात्रवृत्ति',         category:'govt', emoji:'🎓', desc:'Central and state scholarship apply and track',                    price:149,   priceLabel:'₹149',     agentPrice:'₹300–₹700',    sla:'Same day',caRequired:false, phase:2,               tags:['scholarship','student','NSP'] },

  // ── BUSINESS ──────────────────────────────────────────────────
  { slug:'sole-prop',    name:'Sole Proprietorship',      nameHindi:'एकल व्यापार',        category:'business', emoji:'👤', desc:'GST + current account guidance for solo traders',                price:999,   priceLabel:'₹999',     agentPrice:'₹2,000–₹5,000',sla:'Same day',caRequired:false, phase:2,               tags:['sole','proprietor','solo'] },
  { slug:'partnership',  name:'Partnership Firm Reg.',    nameHindi:'साझेदारी',           category:'business', emoji:'🤝', desc:'Partnership deed drafting and firm registration',                price:1999,  priceLabel:'₹1,999',   agentPrice:'₹5,000–₹10,000',sla:'3 days', caRequired:true,  phase:2,               tags:['partnership','deed','firm'] },
  { slug:'llp',          name:'LLP Registration',         nameHindi:'LLP पंजीकरण',        category:'business', emoji:'🏛️', desc:'Incorporate LLP — MCA21 filing, DPIN, DSC',                      price:3999,  priceLabel:'₹3,999',   agentPrice:'₹8,000–₹20,000',sla:'5 days', caRequired:true,  phase:3,               tags:['LLP','incorporate','MCA'] },
  { slug:'pvt-ltd',      name:'Pvt Ltd Company Reg.',     nameHindi:'प्राइवेट लिमिटेड',   category:'business', emoji:'🏢', desc:'Incorporate Pvt Ltd — SPICe+ filing, DIN, DSC',                  price:5999,  priceLabel:'₹5,999',   agentPrice:'₹12,000–₹30,000',sla:'7 days',caRequired:true,  phase:3,               tags:['company','SPICe','DIN','MCA'] },
  { slug:'opc',          name:'One Person Company',       nameHindi:'OPC',                 category:'business', emoji:'👤', desc:'Incorporate OPC for solo entrepreneurs',                         price:4999,  priceLabel:'₹4,999',   agentPrice:'₹10,000–₹25,000',sla:'7 days',caRequired:true,  phase:3,               tags:['OPC','solo','incorporate'] },
  { slug:'msme',         name:'MSME / Udyam Reg.',        nameHindi:'उद्यम पंजीकरण',      category:'business', emoji:'🏭', desc:'Udyam certificate — unlock govt benefits, loans, subsidies',     price:299,   priceLabel:'₹299',     agentPrice:'₹500–₹1,500',  sla:'2 hrs',   caRequired:false, phase:1, popular:true,  tags:['MSME','Udyam','certificate','subsidy'] },
  { slug:'trade-lic',    name:'Trade / Shop Licence',     nameHindi:'दुकान लाइसेंस',      category:'business', emoji:'🏪', desc:'Municipal trade licence or FSSAI basic registration',            price:399,   priceLabel:'₹399',     agentPrice:'₹800–₹2,000',  sla:'2 days',  caRequired:false, phase:2,               tags:['trade','shop','licence','municipal'] },
  { slug:'trademark',    name:'Trademark Registration',   nameHindi:'ट्रेडमार्क',          category:'business', emoji:'™️', desc:'Brand name or logo TM application — 1 class included',          price:3499,  priceLabel:'₹3,499',   agentPrice:'₹8,000–₹20,000',sla:'5 days', caRequired:true,  phase:3,               tags:['trademark','brand','IP','logo'] },
  { slug:'roc-filing',   name:'ROC Annual Filing (MCA)',  nameHindi:'ROC फाइलिंग',         category:'business', emoji:'📑', desc:'AOC-4 + MGT-7 annual compliance for private companies',          price:1999,  priceLabel:'₹1,999',   agentPrice:'₹5,000–₹12,000',sla:'3 days', caRequired:true,  phase:3,               tags:['ROC','MCA','AOC','MGT'] },
  { slug:'din-dsc',      name:'DIN / DSC Services',       nameHindi:'DIN / DSC',           category:'business', emoji:'🔑', desc:'Director ID Number and Digital Signature Certificate',           price:599,   priceLabel:'₹599',     agentPrice:'₹1,000–₹2,500',sla:'Same day',caRequired:false, phase:2,               tags:['DIN','DSC','director','digital'] },
  { slug:'iec',          name:'Import-Export Code',       nameHindi:'IEC कोड',             category:'business', emoji:'🌍', desc:'IEC registration for international trade',                       price:699,   priceLabel:'₹699',     agentPrice:'₹1,500–₹3,000',sla:'Same day',caRequired:false, phase:2,               tags:['IEC','export','import','DGFT'] },
  { slug:'fssai',        name:'FSSAI Food Licence',       nameHindi:'FSSAI लाइसेंस',       category:'business', emoji:'🍽️', desc:'Basic, state, or central FSSAI licence for food businesses',    price:799,   priceLabel:'₹799',     agentPrice:'₹2,000–₹5,000',sla:'2 days',  caRequired:false, phase:2,               tags:['FSSAI','food','restaurant','licence'] },

  // ── ACCOUNTING ───────────────────────────────────────────────
  { slug:'bookkeeping',  name:'Monthly Bookkeeping',      nameHindi:'बुककीपिंग',          category:'accounting', emoji:'📒', desc:'Income, expenses, bank reconciliation every month',           price:999,   priceLabel:'₹999/mo',  agentPrice:'₹3,000–₹8,000/mo',sla:'Ongoing',caRequired:false, phase:2, recurring:true, tags:['monthly','accounts','bookkeeping'] },
  { slug:'tally-setup',  name:'Tally / Accounting Setup', nameHindi:'Tally सेटअप',        category:'accounting', emoji:'💻', desc:'Chart of accounts, Tally Prime configuration, training',     price:1499,  priceLabel:'₹1,499',   agentPrice:'₹3,000–₹8,000', sla:'2 days',  caRequired:false, phase:2,               tags:['Tally','setup','chart','accounts'] },
  { slug:'pnl',          name:'P&L and Balance Sheet',    nameHindi:'P&L तैयार',           category:'accounting', emoji:'📊', desc:'Annual financial statements for MCA / bank submissions',      price:1499,  priceLabel:'₹1,499',   agentPrice:'₹3,000–₹8,000', sla:'3 days',  caRequired:true,  phase:3,               tags:['P&L','balance sheet','financials'] },
  { slug:'payroll',      name:'Payroll Processing',       nameHindi:'वेतन प्रसंस्करण',    category:'accounting', emoji:'💵', desc:'Salary slips, PF/ESIC deductions, professional tax calc',     price:799,   priceLabel:'₹799/mo',  agentPrice:'₹2,000–₹5,000/mo',sla:'Ongoing',caRequired:false, phase:2, recurring:true, tags:['payroll','salary','PF','ESIC'] },
  { slug:'tds-compute',  name:'TDS Computation',          nameHindi:'TDS गणना',            category:'accounting', emoji:'🧮', desc:'Monthly TDS liability working and challan payment',            price:499,   priceLabel:'₹499/mo',  agentPrice:'₹1,500–₹4,000/mo',sla:'Ongoing',caRequired:false, phase:2, recurring:true, tags:['TDS','challan','monthly'] },
  { slug:'cashflow',     name:'Cash Flow Statement',      nameHindi:'नकदी प्रवाह',         category:'accounting', emoji:'💹', desc:'Annual cash flow statement for MCA or bank submissions',      price:999,   priceLabel:'₹999',     agentPrice:'₹3,000–₹8,000', sla:'3 days',  caRequired:true,  phase:3,               tags:['cash flow','MCA','bank'] },
  { slug:'cma-report',   name:'Project / CMA Report',     nameHindi:'CMA रिपोर्ट',         category:'accounting', emoji:'📈', desc:'Projected financials for bank loans — CMA format',            price:2499,  priceLabel:'₹2,499',   agentPrice:'₹8,000–₹20,000',sla:'5 days',  caRequired:true,  phase:3,               tags:['CMA','bank loan','projection'] },
  { slug:'virtual-cfo',  name:'Virtual CFO Service',      nameHindi:'Virtual CFO',         category:'accounting', emoji:'👔', desc:'Monthly advisory, MIS reports, board presentations for SMEs', price:4999,  priceLabel:'₹4,999/mo',agentPrice:'₹15,000–₹40,000/mo',sla:'Ongoing',caRequired:true, phase:3,               tags:['CFO','advisory','MIS','SME'] },

  // ── LEGAL ─────────────────────────────────────────────────────
  { slug:'rent-agreement',name:'Rent Agreement',          nameHindi:'किराया समझौता',      category:'legal', emoji:'📋', desc:'11-month rent agreement drafted and ready in 2 hours',           price:299,   priceLabel:'₹299',     agentPrice:'₹500–₹1,500',  sla:'2 hrs',   caRequired:false, phase:1, popular:true,  tags:['rent','tenant','landlord','agreement'] },
  { slug:'sale-deed',    name:'Sale Deed Review',         nameHindi:'बिक्री दस्तावेज़',   category:'legal', emoji:'🏘️', desc:'Property sale deed review — risks identified, flags raised',      price:999,   priceLabel:'₹999',     agentPrice:'₹3,000–₹8,000',sla:'3 days',  caRequired:true,  phase:3,               tags:['property','sale','deed','review'] },
  { slug:'poa',          name:'Power of Attorney',        nameHindi:'मुख्तारनामा',        category:'legal', emoji:'📝', desc:'General or specific PoA for property, banking, legal matters',   price:499,   priceLabel:'₹499',     agentPrice:'₹1,000–₹3,000',sla:'2 hrs',   caRequired:false, phase:2,               tags:['POA','attorney','property'] },
  { slug:'will',         name:'Will Drafting',            nameHindi:'वसीयत',               category:'legal', emoji:'📜', desc:'Legal will preparation with notarisation guidance',               price:999,   priceLabel:'₹999',     agentPrice:'₹3,000–₹8,000',sla:'2 days',  caRequired:false, phase:2,               tags:['will','estate','inheritance'] },
  { slug:'noc',          name:'NOC Drafting',             nameHindi:'NOC',                 category:'legal', emoji:'✅', desc:'No-objection certificate for property, employment, education',   price:199,   priceLabel:'₹199',     agentPrice:'₹400–₹1,000',  sla:'2 hrs',   caRequired:false, phase:1,               tags:['NOC','no objection','certificate'] },
  { slug:'affidavit',    name:'Affidavit Drafting',       nameHindi:'हलफनामा',             category:'legal', emoji:'📄', desc:'Legal affidavit on stamp paper — any purpose',                   price:199,   priceLabel:'₹199',     agentPrice:'₹400–₹800',    sla:'2 hrs',   caRequired:false, phase:1,               tags:['affidavit','stamp','legal'] },
  { slug:'legal-notice', name:'Legal Notice Drafting',    nameHindi:'कानूनी नोटिस',       category:'legal', emoji:'⚖️', desc:'Notice to tenant, employer, debtor — legally drafted',            price:699,   priceLabel:'₹699',     agentPrice:'₹2,000–₹5,000',sla:'Same day',caRequired:true,  phase:3,               tags:['notice','tenant','employer','debt'] },
  { slug:'consumer',     name:'Consumer Complaint',       nameHindi:'उपभोक्ता शिकायत',    category:'legal', emoji:'🛡️', desc:'NCDRC / state consumer forum complaint filing',                  price:499,   priceLabel:'₹499',     agentPrice:'₹1,500–₹4,000',sla:'2 days',  caRequired:false, phase:2,               tags:['consumer','complaint','NCDRC','forum'] },
  { slug:'rti',          name:'RTI Application',          nameHindi:'RTI आवेदन',           category:'legal', emoji:'📢', desc:'Right to Information request to any government department',       price:149,   priceLabel:'₹149',     agentPrice:'₹300–₹700',    sla:'Same day',caRequired:false, phase:2,               tags:['RTI','information','government'] },

  // ── LOANS ─────────────────────────────────────────────────────
  { slug:'mudra',        name:'Mudra Loan Assistance',    nameHindi:'मुद्रा लोन',          category:'loans', emoji:'🏦', desc:'PMMY Shishu/Kishore/Tarun loan application guidance',             price:499,   priceLabel:'₹499',     agentPrice:'₹1,000–₹2,500',sla:'Same day',caRequired:false, phase:2,               tags:['Mudra','PMMY','Shishu','small business'] },
  { slug:'bank-loan-docs',name:'Bank Loan Docs',          nameHindi:'बैंक लोन दस्तावेज़', category:'loans', emoji:'📁', desc:'Prepare complete loan file — P&L, ITR, CMA, projections',        price:1499,  priceLabel:'₹1,499',   agentPrice:'₹4,000–₹10,000',sla:'3 days',  caRequired:true,  phase:3,               tags:['loan','bank','CMA','projection'] },
  { slug:'cibil',        name:'CIBIL Score Review',       nameHindi:'क्रेडिट स्कोर',       category:'loans', emoji:'📊', desc:'Fetch report, explain score, dispute errors dragging it down',   price:199,   priceLabel:'₹199',     agentPrice:'₹400–₹1,000',  sla:'Same day',caRequired:false, phase:1, popular:true,  tags:['CIBIL','credit','score','dispute'] },
  { slug:'credit-fix',   name:'Credit Score Improvement', nameHindi:'क्रेडिट सुधार',      category:'loans', emoji:'📈', desc:'Action plan to improve CIBIL score in 90 days',                  price:499,   priceLabel:'₹499',     agentPrice:'₹1,500–₹4,000',sla:'Same day',caRequired:false, phase:3,               tags:['CIBIL','improve','score','plan'] },
  { slug:'home-loan',    name:'Home Loan Docs',           nameHindi:'होम लोन',             category:'loans', emoji:'🏠', desc:'Income proof, ITR, Form 16 alignment for home loan approval',     price:799,   priceLabel:'₹799',     agentPrice:'₹2,500–₹7,000',sla:'3 days',  caRequired:true,  phase:3,               tags:['home loan','property','bank'] },
  { slug:'cc-od',        name:'CC / OD Limit Guidance',   nameHindi:'CC/OD सुविधा',        category:'loans', emoji:'💳', desc:'Help SMEs set up cash credit or overdraft bank facilities',      price:999,   priceLabel:'₹999',     agentPrice:'₹3,000–₹8,000',sla:'3 days',  caRequired:true,  phase:3,               tags:['CC','OD','overdraft','SME','bank'] },
  { slug:'subsidy',      name:'Govt Subsidy Application', nameHindi:'सब्सिडी आवेदन',      category:'loans', emoji:'🎯', desc:'CGTMSE, PMEGP, Startup India subsidy guidance and application',  price:499,   priceLabel:'₹499',     agentPrice:'₹1,500–₹4,000',sla:'2 days',  caRequired:false, phase:3,               tags:['subsidy','PMEGP','CGTMSE','Startup India'] },

  // ── INSURANCE ─────────────────────────────────────────────────
  { slug:'life-ins',     name:'Life Insurance Advisory',  nameHindi:'जीवन बीमा',          category:'insurance', emoji:'❤️', desc:'Compare term and ULIP plans, assist in application',           price:199,   priceLabel:'₹199',     agentPrice:'Commission-based',sla:'Same day',caRequired:false,phase:3,               tags:['life','term','ULIP','insurance'] },
  { slug:'health-ins',   name:'Health Insurance Advisory',nameHindi:'स्वास्थ्य बीमा',     category:'insurance', emoji:'🏥', desc:'Compare mediclaim and family floater plans',                    price:199,   priceLabel:'₹199',     agentPrice:'Commission-based',sla:'Same day',caRequired:false,phase:3,               tags:['health','mediclaim','family floater'] },
  { slug:'motor-ins',    name:'Motor Insurance Renewal',  nameHindi:'वाहन बीमा',          category:'insurance', emoji:'🚗', desc:'Compare and renew two-wheeler or car insurance',               price:99,    priceLabel:'₹99',      agentPrice:'Commission-based',sla:'Same day',caRequired:false,phase:1, popular:true, tags:['motor','car','bike','renewal'] },
  { slug:'ins-claim',    name:'Insurance Claim Assist',   nameHindi:'बीमा दावा',          category:'insurance', emoji:'📝', desc:'Help file and follow up insurance claims',                      price:499,   priceLabel:'₹499',     agentPrice:'₹1,500–₹4,000',sla:'2 days',  caRequired:false, phase:3,               tags:['claim','insurance','settlement'] },
  { slug:'pmjjby',       name:'PMJJBY / PMSBY',           nameHindi:'PM बीमा योजना',      category:'insurance', emoji:'🛡️', desc:'Govt life and accident insurance scheme enrolment',             price:49,    priceLabel:'₹49',      agentPrice:'₹100–₹300',    sla:'Same day',caRequired:false, phase:3,               tags:['PMJJBY','PMSBY','scheme','govt'] },
]

export function getServicesByCategory(cat: Category): ServiceItem[] {
  return ALL_SERVICES.filter(s => s.category === cat)
}

export function getServiceBySlug(slug: string): ServiceItem | undefined {
  return ALL_SERVICES.find(s => s.slug === slug)
}

export function searchServices(query: string): ServiceItem[] {
  const q = query.toLowerCase().trim()
  if (!q) return ALL_SERVICES
  return ALL_SERVICES.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.nameHindi.includes(q) ||
    s.desc.toLowerCase().includes(q) ||
    s.tags.some(t => t.toLowerCase().includes(q)) ||
    s.category.includes(q)
  )
}

export function getPopularServices(): ServiceItem[] {
  return ALL_SERVICES.filter(s => s.popular)
}

export function getPhase1Services(): ServiceItem[] {
  return ALL_SERVICES.filter(s => s.phase === 1)
}
